### ISSUE TITLE
Add Diploma Education card & 10 th Education card . Under the Education section.

### ISSUE THREAD

**Issue by Shraddhakal** [mahibhai7781/ajaybamande.github.io#16]
1 .Create Diploma Card under the Education section Take reference from previous Engineering education card.
A. Diploma Details:-
Diploma Of Engineering
year 2012 to 2016
Rambhau Lingade Polytechnic College Buldhana, Maharashtra

2. Crete 10th education card under the Education section Take reference from previous Engineering education card.
10th :-
Year 2011 to 2012
Maharashtra State board education.
D. E. S. High school Datala, Buldhana, Maharashtra

Note:- Must Awere all card should be Inline & responsive page.
Check in mobile view as well.

**Comment by mahibhai7781** [comment]
Done
